<include> := <ITransferInterface.ebnf>.<ITransferInterface>

<imports> := "System"
                "System.IO"
                "System.Runtime.Serialization"
                "System.Text"
                "UnityEngine"
                
<nameSpace> := "UnityTest"
<access> := "public"
<className> := "DTOFormatter"

<subinterfaces> := <ITransferInterface>

<subclasses> := <Writer>
                <Reader>
                
<privateMethods> := <Transfer>
                    <Serialize>
                    <Deserialize>
