<imports> := "System"
                "System.Collections.Generic"
                "UnityEngine"
<nameSpace> := "UnityTest"
<access> := "public"
<inherits> := "VectorComparerBase<" <typeVector4> ">"
<floatingPointError> := "0.0"
<fields> := <compareType> <floatingPointError>
<methods> := "Compare(" <vector4> ", " <vector4> ")" (* returns <BOOLEAN_LITERAL>, throws "Exception()" *)
